export * from "./CreateText";
export * from "./NewLine";
export * from "./ReplaceText";
export * from "./ReverseText";
export * from "./Text";
export * from "./TextEndsWith";
export * from "./TextIncludes";
export * from "./TextLength";
export * from "./TextStartsWith";
